name: ci

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  integrity:
    name: integrity
    permissions:
      contents: read
    uses: Sulamtech/devsecops-poc-workflows/.github/workflows/reusable-caller-integrity.yml@a543caef95af9997b07c8e40e68291fa83081e8d # caller integrity detector

  tests:
    name: tests
    permissions:
      contents: read
    uses: Sulamtech/devsecops-poc-workflows/.github/workflows/reusable-maven-ci.yml@a543caef95af9997b07c8e40e68291fa83081e8d # poc-v1.1.0
    with:
      java-version: "21"

  security:
    name: security
    permissions:
      contents: read
      pull-requests: read
    uses: Sulamtech/devsecops-poc-workflows/.github/workflows/reusable-security.yml@a543caef95af9997b07c8e40e68291fa83081e8d # poc-v1.1.1
    with:
      image-name: devsecops-poc-spring-boot
